// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAavi4CuDNdSP260yO4TNaR_80DDBFJa4Q',
    appId: '1:5428660004:web:37f65afb3ddf5dac76d5b1',
    messagingSenderId: '5428660004',
    projectId: 'setap6c',
    authDomain: 'setap6c.firebaseapp.com',
    databaseURL:
        'https://setap6c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'setap6c.appspot.com',
    measurementId: 'G-KYQYNR8T4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEteEikQn6vHBhydo0EI6ereEmTCTd0p4',
    appId: '1:5428660004:android:9c8be7e212a7b65476d5b1',
    messagingSenderId: '5428660004',
    projectId: 'setap6c',
    databaseURL:
        'https://setap6c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'setap6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBErxI8WWXRuqnWVifkWn6SVIzIKWVjzsk',
    appId: '1:5428660004:ios:b1558bcca075851776d5b1',
    messagingSenderId: '5428660004',
    projectId: 'setap6c',
    databaseURL:
        'https://setap6c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'setap6c.appspot.com',
    iosBundleId: 'com.example.automationSoftwareFlutterCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBErxI8WWXRuqnWVifkWn6SVIzIKWVjzsk',
    appId: '1:5428660004:ios:716d2394c77997ea76d5b1',
    messagingSenderId: '5428660004',
    projectId: 'setap6c',
    databaseURL:
        'https://setap6c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'setap6c.appspot.com',
    iosBundleId: 'com.example.automationSoftwareFlutterCode.RunnerTests',
  );
}
